### PR TITLE
Adding drpc4k to wrappers/implementations list

### PR DESCRIPTION
**Pull request by Bluexin**

### CODE REVIEW

**Comment by msciotti** [comment]
Wrapper looks good. My only concern is the binaries in the source code. Could we check them out of the repo and instead pull them from here in your build script?

Our next release will have signed DLLs, and checking those certs for extra security would be awesome when that happens.

**Comment by Bluexin** [comment]
Sure will do.


On Dec 1, 2017 12:57 AM, "Mason Sciotti" <notifications@github.com> wrote:

Wrapper looks good. My only concern is the binaries in the source code.
Could we check them out of the repo and instead pull them from here in your
build script?

Our next release will have signed DLLs, and checking those certs for extra
security would be awesome when that happens.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/discordapp/discord-rpc/pull/72#issuecomment-348359796>,
or mute the thread

**Comment by Bluexin** [comment]
I have changed my build script to automatically extract DLLs from your releases with https://github.com/Bluexin/drpc4k/commit/5ec3c036fc4ca8996380c07c638cc9052e64859c
Currently you don't provide libraries for platforms other than windows, do you plan to do so? I can easily adapt my build script to using those too if and when you do. (currently still hosting linux lib binaries)
I will respect your signed DLLs for when that happens, if I didn't completely move to full custom implementation instead of wrapper yet (which I plan to do in the future).

**Comment by msciotti** [comment]
Yes, our next release will include osx and linux signed binaries as well. Let's keep this PR open until those happen (should be soon).

**Comment by msciotti** [comment]
Newest releases here!

https://github.com/discordapp/discord-rpc/releases/tag/v2.1.0

Lemme know when you update your build script, and I'll merge.

**Comment by Bluexin** [comment]
Done OwO
The signatures checks will have to wait, I have yet to learn how to properly handle that #StudentLyfe

**Pull request merged**
