### PR TITLE
Rename BUILD_EXAMPLES to DISCORD_BUILD_EXAMPLES

### PR DESCRIPTION
**Pull request by bitcynth**
To avoid conflicts with other libraries.

### CODE REVIEW

**Comment by msciotti** [comment]
Sorry I'm a bit late to the party on this one. Is this actually breaking things? Or just a stylistic change?

**Comment by bitcynth** [comment]
It is breaking things for me since I can't decide which libraries build examples if all use BUILD_EXAMPLES, although it could cause people using Discord RPC to get examples they don't want if they turned off `BUILD_EXAMPLES` but the variable name is now `DISCORD_BUILD_EXAMPLES`.

**Comment by Bluexin** [comment]
Maybe having it default to `BUILD_EXAMPLES`'s value would allow for fine-tuning without breaking existing setups?

**Comment by bitcynth** [comment]
As can be seen on line 6 `option(DISCORD_BUILD_EXAMPLES "Build example apps" ON)` the default value is what the default value was on `BUILD_EXAMPLES`.

**Comment by Bluexin** [comment]
What I meant was to keep both, with `DISCORD_BUILD_EXAMPLES` getting the (current) value of `BUILD_EXAMPLES` if unspecified.
This way people would still have the same result without changing their build setup but whoever needs more finetuning can do so.

**Comment by bitcynth** [comment]
oh I suppose that might be an idea, I will check on that.

**Comment by msciotti** [comment]
Sorry this never got taken care of; looks like there was some ongoing discussion to be a bit more backwards compat that never happened. I'm gonna close this PR. This SDK is now technically deprecated, but since this was open pre-that time, if you want to make the changes, I'm OK with it if you wanna re-open the PR.

**Pull request closed without merging**
