### PR TITLE
Add example for visual C#

### LINKED ISSUE #119: Unicode support
Hi,
I am using the C# wrapper form the Unity example but I am not able to correctly display a Unicode string. 

Here are the things I tried so far with no luck:

`private DiscordRpc.RichPresence _discordPresence;`

1. `_discordPresence.details = "öäü+#*'+~!§$%&/()=^°?";`
bug1

2. `_discordPresence.details = Encoding.UTF8.GetString(Encoding.Convert(Encoding.Default, Encoding.UTF8,Encoding.Default.GetBytes("öäü+#*'+~!§$%&/()=^°?")));`
bug2

3. `_discordPresence.details = Encoding.UTF8.GetString(Encoding.UTF8.GetBytes("öäü+#*'+~!§$%&/()=^°?"));`
bug3

4. `_discordPresence.details = Encoding.UTF8.GetString(Encoding.Default.GetBytes("öäü+#*'+~!§$%&/()=^°?"));`
bug4

5. `_discordPresence.details = Encoding.UTF32.GetString(Encoding.Default.GetBytes("öäü+#*'+~!§$%&/()=^°?"));`
bug5

`DiscordRpc.UpdatePresence(ref _discordPresence);`

Is this an issue with the C# binding or is there no support für Unicode in the Rich Presence API ?
If the API supports it, what is the way to get Unicode to display correctly when using C#.

Best regards.

### PR DESCRIPTION
**Pull request by sll552**
This kind of fixes #119 by adding my custom wrapper as new example.

I don't know what else is needed to integrate this properly into the repo, please review and add tasks if needed.

### CODE REVIEW

**Comment by msciotti** [comment]
Hm, interesting. Thank you! If the aim of this PR is to get a C# wrapper in the repo with proper UTF-8 support, perhaps I would suggest PRing your wrapper to the "Wrappers and implementations" section, and having this be the example required that lives in your own repo?

I appreciate the effort you've gone through to get this for us. I'm only slightly hesitant to merge another example simply because I don't want to end up with 12 examples in various languages in the main repo - that was the intent of the PRable wrappers section.

**Comment by sll552** [comment]
I have created it as example because the original wrapper was taken from the unity sample. 
For a full blown C# wrapper repo I guess it would need to support visual C# as well as mono, which I can't test. 
Maybe it is possible to integrate this into the unity example? @snowyote mentioned in #119 that he might be looking into a new wrapper, but I don't know what the status is.

**Comment by msciotti** [comment]
That seems like the most reasonable way to go then. If you can PR the additional code into the existing C#/Unity wrapper such that UTF-8 is properly supported, that would be most helpful. I appreciate your taking the time to create another example for us, but I don't want to set a precedent of adding a bunch to the main repo for the sake of clutter.

**Comment by sll552** [comment]
I can try to adapt the unity files when I get home, but I have no experience with unity. Therefore it would be nice if someone who knows how the example should work would test it with my changes.

I will create a new merge request for the unity changes, then this one can be closed.

**Comment by msciotti** [comment]
No problem! If you can get the ball rolling, we can help get it across the finish line. Thank you for the effort! 👍

**Pull request closed without merging**
