### PR TITLE
Updated README with UE plugin instructions

### PR DESCRIPTION
**Pull request by thejhnz**
Hopefully this will save some time when others want to implement this into their own UE Projects.

### CODE REVIEW

**Comment by msciotti** [comment]
This is very helpful, thank you! If you don't mind, I'll add the details for macOS as well to this PR and then merge this tomorrow.

**Comment by msciotti** [comment]
Dunno what happened with all the whitespace in my commit, but whatever :p Thank you!

**Comment by thejhnz** [comment]
@msciotti Just read the updated docs, the whole plugin folder needs copied not just the .uplugin file.

**Comment by msciotti** [comment]
@thejhnz fixed, sorry!

**Pull request merged**
