### PR TITLE
Add Java Wrapper

### PR DESCRIPTION
**Pull request by Vatuu**
Added reference to Vatuu's Discord-RPC.jar wrapper for Java.

Containing self-contained example, basic tutorial on how to get started and references to official docs.

### CODE REVIEW

**Comment by msciotti** [comment]
Sorry about the brief re-name, was thinking of the wrong PR.

**Comment by msciotti** [comment]
Couple notes. You might want to differentiate names of `DiscordInitialize` to `DiscordInitialize` and `DiscordInitializeSteam` or something like that, if you're specifically making both of them public rather than some overloading magic.

Also, can we pull the dlls out of the source code and build script them instead? Thanks!

**Comment by msciotti** [comment]
On second thought, the name differentiate is kinda whatever. Not a huge breaker one way or the other. But DLL thing for sure 👍

**Comment by Vatuu** [comment]
What's the difference between having it in a remote repository and having it bundled inside the project itself? Drawing it from a remote repository simply to get the binaries seems like simply unnecessary work, especially because you'd need to set up a new jitpack/maven/gradle access thingy.

**Comment by hugmanrique** [comment]
I believe it's for security purposes. Some people might be concerned about running a dll they downloaded from the internet and may prefer to `make` it themselves.

**Comment by msciotti** [comment]
It's also that the binary in your repository could be changed without someone knowing. It's better to just build from our source/pull from our releases, because then any user would be guaranteed to be both up to date with our latest release, and guaranteed that it's the official binary.

**Comment by Vatuu** [comment]
Updated it to latest version and moved the binaries to a custom repository containing the builds from the actual rpc repository.

**Comment by msciotti** [comment]
Thank you for making that change. Much appreciated!

**Pull request merged**
