### PR TITLE
Added java binding

### PR DESCRIPTION
**Pull request by MinnDevelopment**

### CODE REVIEW

**Comment by msciotti** [comment]
Binding looks good. My only concern is the binaries in the source code. Could we check them out of the repo and instead pull them from here in your build script?

Our next release will have signed DLLs, and checking those certs for extra security would be awesome when that happens.

**Comment by MinnDevelopment** [comment]
I have moved out the libraries to a separate repository so I can easily update it later https://github.com/MinnDevelopment/discord-rpc-release

**Comment by msciotti** [comment]
This looks good. We have some new signed releases as well for your updating.

https://github.com/discordapp/discord-rpc/releases

Lemme know when you update the binaries in the other repo and I'll merge.

**Comment by MinnDevelopment** [comment]
Binaries are updated and I'll be looking into an automated build process.

**Comment by Bluexin** [comment]
Look at what I did in my gradle build script if you want, it pulls from releases and unpacks everything in a proper directory structure for jna

**Comment by MinnDevelopment** [comment]
If you want to make a PR to the repository I'd have no problem with it. This will be a busy few weeks for me so idk when I'll find time.

**Comment by Bluexin** [comment]
Too bad I have little time too :p
I'll try to do it if I find the time to, but don't expect it too much (that and I might just forget about it)

**Pull request merged**
