### PR TITLE
Unity il2cpp support

### PR DESCRIPTION
**Pull request by msciotti**
Trying to support https://github.com/discordapp/discord-rpc/issues/243

### CODE REVIEW

**Comment by msciotti** [comment]
@dylanh724 and @joshpeterson: This seems to be on the path to working. All the Discord-related stuff works just fine in both Mono and il2cpp. Still working on the UnityEvent stuff.

**Comment by dylanh724** [comment]
Hmm, I could only get this working in the editor -- what is your build info?

image

image

**Comment by joshpeterson** [comment]
The error message here from IL2CPP is not too helpful. It would be nice if it happened to mention the name of the method that is causing the problem. I'm going to add this to the error message for a future Unity release.

@dylanh724: It is possible for you to patch the source code in your local Unity installation to add this information to the error message. Here is how to do it:

Look for the Data\il2cpp\libil2cpp\vm\PlatformInvoke.cpp file in your editor installation. In the function named `PlatformInvoke::MarshalDelegate` in that file, look for the code snippet which looks like this:

```c++
// Okay, we cannot marshal it for some reason. Figure out why.
if (Method::IsInstance(d->method))
    vm::Exception::Raise(vm::Exception::GetNotSupportedException("IL2CPP does not support marshaling delegates that point to instance methods to native code."));
```

You can replace that code with this code:

```c++
std::string methodName = il2cpp::vm::Method::GetFullName(d->method);
// Okay, we cannot marshal it for some reason. Figure out why.
if (Method::IsInstance(d->method))
{
    std::string errorMessage = "IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: " + methodName;
    vm::Exception::Raise(vm::Exception::GetNotSupportedException(errorMessage.c_str()));
}
```

Then build the player for IL2CPP in the editor again. When the error happens, you should see the full name of the method that is supposed to be marshaled, but is not able to be marshaled correctly. Hopefully that will help track down the remaining issue.

**Comment by dylanh724** [comment]
We just had a patch in our game - Heads up, I'll need a couple days to get the time to test this again~

**Comment by joshpeterson** [comment]
@dylanh724 No, I think this is the only place this error message occurs. Regarding .bak files, Unity will only compile and use .cpp files, so that should not have an impact.

Is it possible for you to send me the project or submit it via a bug report to us at Unity? I can have a look at it and try to determine what is wrong.

**Comment by dylanh724** [comment]
@joshpeterson the change reflects now -- however, I am getting this error that seems to trace back straight to that file changed: https://pastebin.com/gaH0Ue3p

For clarity, here is what was changed including a bit of the block around it:

```c++
Il2CppMethodPointer reversePInvokeWrapper = MetadataCache::GetReversePInvokeWrapperFromIndex(d->method->methodDefinition->reversePInvokeWrapperIndex);
if (reversePInvokeWrapper == NULL)
{
	// Okay, we cannot marshal it for some reason. Figure out why.
	if (Method::IsInstance(d->method))
	{
		std::string errorMessage = "IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: " + methodName;
		vm::Exception::Raise(vm::Exception::GetNotSupportedException(errorMessage.c_str()));
	}

	vm::Exception::Raise(vm::Exception::GetNotSupportedException("To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition."));
}
```

**Comment by joshpeterson** [comment]
@dylanh724 I think you need one more line:

```c++
std::string methodName = il2cpp::vm::Method::GetFullName(d->method);
```

This should be just above this line:

```c++
std::string errorMessage = "IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: " + methodName;
```

**Comment by dylanh724** [comment]
@joshpeterson Oh man, missed that copy+paste. Got it:

```csharp
NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: DiscordMgr::OnReady
  at DiscordController.OnEnable () [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by joshpeterson** [comment]
Cool! So that indicates the `OnReady` method in the `DiscordMgr` class is still an instance method. That should be changed to be a static method as well.

**Comment by msciotti** [comment]
Hm, that's odd. `OnReady` is what I was mainly testing with, as it's the first callback fired after connecting.

To compare two calls:

```cs
// Not working?
[MonoPInvokeCallback(typeof(OnReadyInfo))]
 public static void ReadyCallback(ref DiscordUser connectedUser) { }
 public delegate void OnReadyInfo(ref DiscordUser connectedUser);

// Working
[MonoPInvokeCallback(typeof(OnErrorInfo))]
 public static void ErrorCallback(int errorCode, string message) { }
 public delegate void OnErrorInfo(int errorCode, string message);

// Handlers

public struct EventHandlers
{
  public OnReadyInfo readyCallback;
  public OnDisconnectedInfo disconnectedCallback;
  public OnErrorInfo errorCallback;
  public OnJoinInfo joinCallback;
  public OnSpectateInfo spectateCallback;
  public OnRequestInfo requestCallback;
}
```

It all seems to look legit? I did just realize that the two ready functions had different names for their variable, which I just fixed, but I feel like that shouldn't cause this error?

**Comment by dylanh724** [comment]
@joshpeterson The main reason why this is awkward is because they have a `public struct EventHandlers` - it makes things a bit awkward. I can't redirect the callbacks straight to my own because Discord uses the EventHandlers for some sealed class.

```csharp
// DiscordController.cs
handlers = new DiscordRpc.EventHandlers();
handlers.readyCallback += s_discordMgr.OnReady;
[...]
```
This is what I tried before -- if I could just skip the handlers, I could probably figure this out.

**Comment by joshpeterson** [comment]
@dylanh724 I don't think the `readyCallback` field in the `EventHandlers` struct needs to be static. But the `OnReady` method in the `DiscordMgr` class _does_ need to be static. Can you provide the code for the `DiscordMgr` class here so that I can have a look at it?

**Comment by dylanh724** [comment]
DiscordMgr is my own script (it was getting a bit confusing with the statics, leaving DiscordMgr my final callback).

Here are the scripts I use, watere down a bit as best as my 3am mind can do @joshpeterson 
[drpc-scripts.zip](https://github.com/discordapp/discord-rpc/files/2563128/drpc-scripts.zip)

I'll check here again in the morning (GMT+8)

**Comment by joshpeterson** [comment]
@dylanh724 This is rather confusing. It looks like the code you have should work. I don't see `OnReady` being marshaled as a callback for native code anywhere. When you have a chance, can you send me the full Unity project? I might be able to debug it and see what is wrong.

**Comment by dylanh724** [comment]
@joshpeterson GOT IT WORKING! I had a bad build, so tested an old build by accident. I really shouldn't be doing this at 3am ;D 

But yeah, works (the exact code I sent you)! So this PR needs their callbacks to be static with that [] mono attribute.

image

@msciotti Check out the zip file above for a working build example. My code has a `DiscordMgr` which you can decide if you want or don't want. I added this because the static callbacks get confusing and you want to send it to a singleton / non-static instance somewhere. If you don't touch the callbacks, **this makes UPDATING wayy easier** (and the overall flow less confusing) if you leave `DiscordMgr` as the end-users logic. This also means they can name their callbacks whatever they want with minimal master repo changes. Anyway, feel free to cherry pick what you feel is best:

* `DiscordRpc` is untouched
* `DiscordController` handles init + the Handler callbacks. **The handler callbacks at OnEnable need to be STATIC with that `[]` attribute** above it. It then needs to be sent to a SINGLETON (since it's static), assuming you want to cache things and save things in an instance. In my example, I then callback to my `DiscordMgr` custom logic that handles the non-static (final) callbacks. You could optionally keep it in the current `DiscordController`, **but this would encourage end-users to make custom logic, which makes updating very difficult**.
* `DiscordMgr` has a singleton to call from the `DiscordController` static callback. It has the traditional callbacks you saw in the original (non-static) `DiscordController` before the il2cpp changes. Moved to this file to separate custom logic. Can be named something arbitrary.

**Comment by joshpeterson** [comment]
@dylanh724 That is great to hear! I'm happy you have this working now.

> About that Bounty

I'd rather not accept it - I'm just doing my job at Unity. :) If you still want to pay it though, I'd suggest a charity, maybe [Girls Who Code](https://girlswhocode.com/)?

**Comment by msciotti** [comment]
Seconded. If you really feel like it, Girls Who Code is fantastic. Thank you both for your help!

**Comment by msciotti** [comment]
@dylanh724 it seems like you ran into a similar issue that I did, which was errors when trying to assign the callbacks to methods in a singleton `GameManager` class.

I think we may want to get somewhere in the middle here. The existing code _does_ work as is, and i don't want to implement a specific pattern in the example for folks who may want an example a little more basic.

Is there a way that we can structure things where the existing code works, and it's also easily extended to a use case like yours?

**Comment by dylanh724** [comment]
> Is there a way that we can structure things where the existing code works, and it's also easily extended to a use case like yours?

The alternative would be in `DiscordController` to put the static callbacks at the top (or above each callback -- but maybe better at top since the average user won't ever touch them) and make a singleton for DiscordController (if there's not 1 already - I don't think so). Then change the non-static callbacks to private. And import AOT. 

Or use an anonymous callback `() =>`, but it could get bloaty. Probably not. Something like ...

```csharp
// ############################################################
//DiscordController
// ############################################################
using UnityEngine;
using AOT;

#region "Core vars"
public string applicationId;
public string optionalSteamId;
public static DiscordController s_discordCtrl;
private DiscordRpc.EventHandlers handlers;
public DiscordRpc.RichPresence presence = new DiscordRpc.RichPresence();
public DiscordRpc.DiscordUser joinRequest;
#endregion 

#region "Demo Vars"
public int clickCounter;
public DiscordJoinEvent onJoin;
public DiscordJoinEvent onSpectate;
public DiscordJoinRequestEvent onJoinRequest;
public UnityEngine.Events.UnityEvent onConnect;
public UnityEngine.Events.UnityEvent onDisconnect;
public UnityEngine.Events.UnityEvent hasResponded;
// <And those serialization fields - seems like I deleted them>
#endregion

#region "Static il2cpp callbacks"
[MonoPInvokeCallback(typeof(DiscordRpc.OnReadyInfo))]
public static void OnReadyStatic(ref DiscordRpc.DiscordUser connectedDiscordUser)
{ s_discordCtrl.OnReady(ref connectedDiscordUser); }

[MonoPInvokeCallback(typeof(DiscordRpc.OnDisconnectedInfo))]
public static void OnDisconnectedStatic(int errorCode, string message)
{ DiscordController.s_discordCtrl.OnDisconnected(errorCode, message); }

[MonoPInvokeCallback(typeof(DiscordRpc.OnErrorInfo))]
public static void OnErrStatic(int errorCode, string message)
{ DiscordController.s_discordCtrl.OnErr(errorCode, message); }

[MonoPInvokeCallback(typeof(DiscordRpc.OnJoinInfo))]
public static void OnOtherJoinByPublicInvStatic(string encryptedSecret)
{ DiscordController.s_discordCtrl.OnOtherJoinByPublicInv(encryptedSecret); }

[MonoPInvokeCallback(typeof(DiscordRpc.OnRequestInfo))]
public static void OnMyReqToJoinOtherResStatic(ref DiscordRpc.DiscordUser request)
{ DiscordController.s_discordCtrl.OnMyReqToJoinOtherRes(ref request); }

[MonoPInvokeCallback(typeof(DiscordRpc.OnSpectateInfo))]
public static void OnOtherSpectateStatic(string encryptedSecret)
{ DiscordController.s_discordCtrl.OnOtherSpectate(encryptedSecret); }
#endregion

#region "Demo Callbacks"
private void OnReady(ref connectedDiscordUser)
{
    Debug.Log("[DiscordCtrl] @ OnReady"];
}

// <...and the other callbacks that are normally here - just changed callback to private>
#endregion 

#region "init/end"
private void Awake()
{
    Debug.Log("[DiscordController] @ Awake: Singleton+Persist");

    // Singleton + Persist
    if (s_discordCtrl == null)
    {
        s_discordCtrl = this;
        DontDestroyOnLoad(this.gameObject);
    }
    else if (this != s_discordCtrl)
        Destroy(gameObject);
}

private void OnEnable()
{
    // <The usual stuff>
}

private void OnDisable()
{
    // <The usual shutdown stuff>
}
#endregion 
```

^ This is cherry picked from both of my scripts and added back some of the demo items, but I may be missing some or syntax may be slightly off: Needs some verification. Something like this should work, though.

**Comment by MichalPetryka** [comment]
When will we get new release with this included?

**Comment by msciotti** [comment]
I wanted to try and roll a release together with this + choosing which pipe number to open to support choosing the Discord client to connect to. However, the Windows side of things hung me up on that other PR. Let me take some of Dylan's suggestions above and work on the example, and I can merge + release this this week.

**Comment by msciotti** [comment]
Alright, so I've been trying to poke at this _a lot_. I've gotten to more or less the same place that I was at before, which I'm not sure is the fault of the DiscordRpc stuff but perhaps just my unfamiliarity with doing this stuff in Unity the right way.

I was going about refactoring some stuff into a `DiscordManager` singleton. It looks roughly like this:

```cs
public class DiscordManager
{
    private static DiscordManager _instance;
    public static DiscordManager Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = new DiscordManager();
            }
            return _instance;
        }
    }

    public void Ready(ref DiscordRpc.DiscordUser connectedUser)
    {
        Debug.Log(string.Format("Discord: connected to {0}#{1}: {2}", connectedUser.username, connectedUser.discriminator, connectedUser.userId));
        // onConnect.Invoke();
    }
}
```

I can assign callbacks without issue:

```cs
 handlers = new DiscordRpc.EventHandlers();
 handlers.readyCallback += DiscordManager.Instance.Ready;
```

All this code runs perfectly fine, and callbacks fire. No need to change where the `MonoPInvoke` stuff is done. Where I run into issues that I cannot debug is when I try to invoke the `UnityEvent` from within the singleton. I get no errors; Unity just freezes until I force close it.

For the time being, I'm planning to merge this as-is. It will support compiling with il2cpp, and the example runs as expected. I do not know why the `UnityEvent.Invoke()` stuff is crashing. Perhaps @joshpeterson can shed some light there? I'm more or less out of ideas when it comes to trying to support a singleton GameManager type implementation properly 😕

**Comment by dylanh724** [comment]
@msciotti I think you have a typo
```csharp
if (_instance == null)
    _instance = new DiscordManager();
```
should probably be
```csharp
if (_instance == null)
    _instance = this;
```

**Comment by MichalPetryka** [comment]
Unity freezes when you have infinite loop

**Comment by joshpeterson** [comment]
@msciotti Sorry, I don't have any ideas about why this causes a freeze.

**Comment by msciotti** [comment]
Merging this to at least have a supporting release. I will continue to tinker with examples when I have time.

**Comment by dylanh724** [comment]
As an update, I realized that OnReady callback isn't firing - is it firing for you in your il2cpp Unity tests?

**Pull request merged**
