### PR TITLE
Add Python Lib: pypresence

### PR DESCRIPTION
**Pull request by qwertyquerty**
I believe I have fixed all of the issues you described, if not please tell me and I will fix them as soon as possible. https://github.com/qwertyquerty/pypresence

### CODE REVIEW

**Comment by msciotti** [comment]
This is definitely in a much more complete state, thank you for the changes! Last time I had noted:

- PR your library in alphabetic order: ✅ 
- Installation method/instructions: ✅ 
- macOS connections: ✅ 

Those have all been handled well. This is still a wrapper around the RPC functionality as a whole instead of just Rich Presence. I still believe that Rich Presence functionality should be pulled out into its own project that _only_ handles Rich Presence events and commands, as the rest of it is unusable for...well, almost everyone.

I'm still a bit iffy on the callback event handling. You have the ability to `SUBSCRIBE` and `UNSUBSCRIBE` from events, as well as the commands like `SEND_ACTIVITY_JOIN_REQUEST`. However, if I'm someone looking to use a library to do Rich Presence, I don't know how to use this out of the box. I don't know which events to subscribe to, or what those commands do.

What you probably want to do is take a look at the way the other libraries/wrappers handle this, which is wrapping the raw IPC calls in more understandable class methods that do the work for you—like subscribing to the proper events based on which handlers you select for in some sort of `Init()` call—and expose these callbacks through an event system. The js example comes to mind for ease of use:

```js
client.on('ACTIVITY_JOIN', event => {
      // do whatever is needed
});
```

**Comment by qwertyquerty** [comment]
Hmm, I'll look into this event handling. Another thing I want to finish before I will myself declare it complete is Exceptions. I feel like if the client receives an error from the server, it should be raised with some description of what went wrong to help the user easily track down the problem. I will have these fixed very soon and will let you know when I believe it is ready for review again.

**Comment by qwertyquerty** [comment]
Also for your first part, I still want to keep it as one project if that is possible. You may have noticed in the readme at the beginning, I put this:
image

Which redirects you to `Client.set_activity()`

**Comment by msciotti** [comment]
Yeah I do see. I think it might be fine once the Rich Presence portions are more explicitly wrapped in an event handler system and various helper functions.

**Comment by qwertyquerty** [comment]
Alright, rich presence has it's own client now (but can still be done by the original client in order to keep support for projects that used the old version.) Also, event handling has been added and documented, here you go: https://github.com/qwertyquerty/pypresence/blob/master/README.md#events

Does this all satisfy you?

**Comment by msciotti** [comment]
Yes, this looks great! Apologies for the nitpicky back and forth, but I think this is now in a great state for others to use. Thank you so much! I'll move to the correct alphabetical order after merging, lol.

**Pull request merged**
