### PR TITLE
Add IPC wrapper written in Python to community implementations

### PR DESCRIPTION
**Pull request by MashMB**

### CODE REVIEW

**Comment by msciotti** [comment]
This is a great start—thank you for the work on this! That being said, it doesn't really fully wrap the SDK functionality; it's missing event handler binding, for example.

Some of the exposed functions also aren't quite there. the `send_*_rich_presence()` functions don't allow you to set timestamps, secrets, party information, etc. without digging into the "source" code.

It's a fair wrapper for basic Rich Presence info, but to be included, I think we'd want parity with the native SDK, much like the other libraries include.

If others have strong reasons/opinions as to why this should be included, please comment.

**Comment by msciotti** [comment]
(as a side note, saw you had `untested` for mac. Works great on macOS for me 👍 )

**Comment by MashMB** [comment]
Hello, thank you for a quick response. 

I am fully aware that it do not cover all SDK functionality, as an open source piece of software it covers only my point of interests (for the next project), that’s why there is no PyPi package as well. I was trying to keep code clean and readable to make it easily extendable. Maybe word “wrapper” was abused, it is just a simple RPC client. 

As you mentioned above if there will be enough reasons/opinions about it, I will cover rest of the SDK functionality. As I know, Python is not so common choice to create games and other programs that need Discord integration but maybe I am wrong.

I feel really thankful for testing it on MacOS. 

Cheers

**Comment by msciotti** [comment]
I think to include it alongside the others, we'd want it to cover all functionality. With that, I understand that using Python is not exactly a common choice for creating games. I'm going to close the PR for now.

If you decide in the future that you would like to fully wrap the SDK, please open another PR when it's completed!

**Pull request closed without merging**
