### PR TITLE
Exported Discord_Register and Discord_RegisterSteam

### PR DESCRIPTION
**Pull request by Vatuu**
Edited the discord-RPC to export the ``Discord_Register(String appId, String cmd)`` methods, to allow customization of the executable path on a join game callback.

This allows more bootup possibilities for java apps (Classpath, flags etc.) and the option of having multiple executable files inside a game director, more advanced properties/flags and variable paths.

Also moved the ``discord_register.h`` file to include, for developer convenience.

### CODE REVIEW

**Comment by msciotti** [comment]
Sorry for the lack of response. Totally my fault. This seems fine to me—directly exporting the register functions is probably better than pseudo-hiding them in source. I have no qualms with this as long as it doesn't break existing auto-register functionality—I can pull the PR and test.

Would appreciate @snowyote looking at this though, as he knows this stuff better than I.

**Comment by msciotti** [comment]
Small thought - should we just move the functions into the general `discord-rpc.h` file? Keep it all in one place?

**Comment by Vatuu** [comment]
Sure, as long as I can finally properly use it.

**Comment by Vatuu** [comment]
Although, since the main .h file already has initializeSteam and the normal initialize method, 2 additional files could confuse people

**Comment by msciotti** [comment]
Yeah, I don't feel strongly either way. Keeping it separate is fine enough—it all gets wrapped up in the SDK anyway.

Compiled from source and everything worked as promised 👍  I'll poke for a quick review from the expert.

**Comment by snowyote** [comment]
Looks good to me!  I'll check after merge if we also want DISCORD_EXPORT on the Mac implementations as well.

**Comment by Vatuu** [comment]
I'll update my discord-rpc.jar with temporary artifacts from the source directly for now, until a proper release is uh... released. Since I need these functions ASAP.

**Pull request merged**
