### PR TITLE
Provide fake DllMain declaration to fix missing-declarations warning

### PR DESCRIPTION
**Pull request by janisozaur**
Sorry about the flurry of PRs, just fixing the items as I discover them.

This is mutually exclusive with https://github.com/discordapp/discord-rpc/pull/129, please pick the version you like better or provide comments.

### CODE REVIEW

**Comment by janisozaur** [comment]
Using this fix, I finally have a green result on our mingw job: https://travis-ci.org/janisozaur/OpenRCT2/jobs/341619659

**Comment by janisozaur** [comment]
Hi @msciotti @crmarsh any chance of having this merged or getting some feedback?

**Comment by msciotti** [comment]
@snowyote will be the one to review this—I've pinged him. This looks...odd to me, but my experience in this stuff is lesser.

**Comment by snowyote** [comment]
Thanks for the fix!  I am generally averse to preprocessor noise so I think I prefer this one.

**Comment by janisozaur** [comment]
The issue here is if building with mingw and `-Wmissing-declarations` you have to have a forward declarations as a "proof" you are exporting a function or it has to be marked as `static` (or in anonymous namespace).

For obvious reasons, this cannot be marked as `static`, but neither `windows.h` nor any of its includees forward-declares such a function, which creates the need to work around this issue.

**Comment by janisozaur** [comment]
@snowyote thanks for merging.

**Pull request merged**
