### PR TITLE
Add link to lua-discordRPC (LuaJIT bindings)

### PR DESCRIPTION
**Pull request by pfirsich**
https://github.com/pfirsich/lua-discordRPC

### CODE REVIEW

**Comment by msciotti** [comment]
This looks solid, thank you! Need to add the `userId, username, discriminator, avatar` fields in the `ready()` parameters—we send those now—but I'll merge this as-is and you can update that quickly. Thank you!

**Comment by pfirsich** [comment]
I actually looked into it and it seems that I wrote my bindings for version 2.1.0 from January. I will go through the changes and update my bindings right now. I added that version to the README too to avoid possible confusion. Sorry.

**Comment by msciotti** [comment]
All good—thank you!

**Comment by pfirsich** [comment]
I don't mean to spam you, but it's up to date now. Thanks for the quick merge btw.!

**Pull request merged**
