### PR TITLE
Update C# wrapper with visual C# compatible version

### LINKED ISSUE #119: Unicode support
Hi,
I am using the C# wrapper form the Unity example but I am not able to correctly display a Unicode string. 

Here are the things I tried so far with no luck:

`private DiscordRpc.RichPresence _discordPresence;`

1. `_discordPresence.details = "öäü+#*'+~!§$%&/()=^°?";`
bug1

2. `_discordPresence.details = Encoding.UTF8.GetString(Encoding.Convert(Encoding.Default, Encoding.UTF8,Encoding.Default.GetBytes("öäü+#*'+~!§$%&/()=^°?")));`
bug2

3. `_discordPresence.details = Encoding.UTF8.GetString(Encoding.UTF8.GetBytes("öäü+#*'+~!§$%&/()=^°?"));`
bug3

4. `_discordPresence.details = Encoding.UTF8.GetString(Encoding.Default.GetBytes("öäü+#*'+~!§$%&/()=^°?"));`
bug4

5. `_discordPresence.details = Encoding.UTF32.GetString(Encoding.Default.GetBytes("öäü+#*'+~!§$%&/()=^°?"));`
bug5

`DiscordRpc.UpdatePresence(ref _discordPresence);`

Is this an issue with the C# binding or is there no support für Unicode in the Rich Presence API ?
If the API supports it, what is the way to get Unicode to display correctly when using C#.

Best regards.

### PR DESCRIPTION
**Pull request by sll552**
Replaces #123 and fixes #119

As I am not able to test Unity, please review and test my changes.

### CODE REVIEW

**Comment by msciotti** [comment]
Sorry for the delay. I've got your PR open in unity, and it's throwing some errors. I'll take a deeper look to see what's up.

**Comment by msciotti** [comment]
Few things I needed to change to get working:

```cs
internal IntPtr StrToPtr(string input, int maxbytes)
        {
            if (string.IsNullOrEmpty(input)) return IntPtr.Zero;
            var convstr = StrClampBytes(input, maxbytes);
            var convbytecnt = Encoding.UTF8.GetByteCount(convstr);
            var buffer = Marshal.AllocHGlobal(convbytecnt);
            _buffers.Add(buffer);
            Marshal.Copy(Encoding.UTF8.GetBytes(convstr), 0, buffer, convbytecnt);
            return buffer;
        }
```

This needed to be pulled out of `GetStruct()` method. It also complained without a few more using directives:

```cs
using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;
```

I've got those changes in a commit in your branch here, but don't wanna push them in case your stuff gets messed up. Could you try those changes in your own project and see if it still does what you need?

@snowyote put an eye on this when you have a moment, to make sure I'm not bamboozling myself.

**Comment by sll552** [comment]
I guess that these errors are just some M$ specifics that are not supported in mono/unity, fixing those should be no problem. I will get the changes together when I get home.

What I don't understand is why it is complaining about the includes, because Linq should be supported in Unity (at least I found [this)](https://unity3d.college/2017/07/01/linq-unity-developers/) and the others are just really basic parts that should be supported by mono. 
I can ditch Linq because I am just using the Last() function for arrays, maybe that's enough to resolve the errors.

**Comment by msciotti** [comment]
Could be my own mistakes in refactoring stuff. The include statements are kinda whatever, more just want to make sure that moving the function out of `GetStruct()` doesn't break anything for you.

**Comment by sll552** [comment]
I hope this fixes everything. 
Somehow the imports got lost in the initial commit, so this should work now.

**Comment by msciotti** [comment]
Your latest commit works great for Unity! The Linq thing must've been my own issue. @snowyote is gonna look at this a little bit more closely, but I can confirm this works for Unity.

**Comment by msciotti** [comment]
Thank you very very much for the work that went into this

**Comment by sll552** [comment]
No problem. I am always glad to help 😃, thanks for merging

**Pull request merged**
