### PR TITLE
[Unreal] Fix for Shipping Builds

### PR DESCRIPTION
**Pull request by oreyg**
This PR will allow developers to make Shipping Builds. 
Misc. changes:
Plugin's code converted to UpperCamelCase, which is standard for UE4.

### CODE REVIEW

**Comment by oreyg** [comment]
Considering https://github.com/discordapp/discord-rpc/issues/89
@snowyote would have to copy libs to 
examples\unrealstatus\Plugins\DiscordRpc\Source\ThirdParty\DiscordRpcLibrary\Win64
examples\unrealstatus\Plugins\DiscordRpc\Source\ThirdParty\DiscordRpcLibrary\Linux
examples\unrealstatus\Plugins\DiscordRpc\Source\ThirdParty\DiscordRpcLibrary\Mac
And copy include files to 
examples\unrealstatus\Plugins\DiscordRpc\Source\ThirdParty\DiscordRpcLibrary\Include

**Comment by snowyote** [comment]
I don't think `git config` will apply to clones, unfortunately.  Can you revert the folder name to lowercase?  You have my apologies for my getting it wrong in the first place! 🙇  If there's an opportunity to rename in the future, I'll make sure to change it to CamelCase at the same time.

**Comment by snowyote** [comment]
Sounds good 👍  Thank you for the PR!

**Comment by oreyg** [comment]
I will setup windows-to-linux cross-compiling using clang toolchain later on, should I commit it here?

**Comment by snowyote** [comment]
Ah, nice =)  I think you may need to open a new pull request once you're ready for it to be merged, but it may allow merging again after you add new commits to your master(?)  I guess we'll see, I'll keep an eye out.

**Comment by CharlotteDunois** [comment]
Pushing new commits to the same branch as the PR will add the new commits to the PR aswell.

**Comment by snowyote** [comment]
Thank you @CharlotteDunois !

**Pull request merged**
